version: '3.6'

services:
  db:
    image: postgres:latest
    container_name: veterinaria_udv
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - veterinary_udv
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: gunicorn -b 0.0.0.0:8000 veterinaria.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - veterinary_udv

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    networks:
      - veterinary_udv
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:

networks:
  veterinary_udv:
    driver: bridge