FROM nginx:latest

RUN apt-get update && apt-get install -y wget tar \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["dockerize", "-wait", "tcp://api:8000", "-timeout", "60s", "nginx", "-g", "daemon off;"]
